#pragma once

#define EMBLIB_UNNEST_NAMESPACES    1

#define EMBLIB_TIME_ALIGN_MILLIS    1
#define EMBLIB_TIME_TICK_MILLIS     1

#define EMBLIB_RTOS_USE_FREERTOS    1
#define EMBLIB_RTOS_SUPPORT_NOTIFICATIONS 1

#define EMBLIB_MATH_USE_EIGEN       1
